# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_manager_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import business_manager_model_pb2 as business__manager__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='business_manager_controller.proto',
  package='com.revolutionlandscaping.businessmanager',
  syntax='proto3',
  serialized_pb=_b('\n!business_manager_controller.proto\x12)com.revolutionlandscaping.businessmanager\x1a\x1c\x62usiness_manager_model.proto\"\xbc\x01\n\x0c\x43ommonAction\x12T\n\x07request\x18\x01 \x01(\x0b\x32\x43.com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest\x12V\n\x08response\x18\x02 \x01(\x0b\x32\x44.com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse\"\xda\x05\n\x0eMainController\x12M\n\x0cget_accounts\x18\x01 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12N\n\rsave_accounts\x18\x02 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12P\n\x0f\x64\x65lete_accounts\x18\x03 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12N\n\rget_employees\x18\x04 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12O\n\x0esave_employees\x18\x05 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12Q\n\x10\x64\x65lete_employees\x18\x06 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12I\n\x08get_jobs\x18\x07 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12J\n\tsave_jobs\x18\x08 \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonAction\x12L\n\x0b\x64\x65lete_jobs\x18\t \x01(\x0b\x32\x37.com.revolutionlandscaping.businessmanager.CommonActionb\x06proto3')
  ,
  dependencies=[business__manager__model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMONACTION = _descriptor.Descriptor(
  name='CommonAction',
  full_name='com.revolutionlandscaping.businessmanager.CommonAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='com.revolutionlandscaping.businessmanager.CommonAction.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='com.revolutionlandscaping.businessmanager.CommonAction.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=299,
)


_MAINCONTROLLER = _descriptor.Descriptor(
  name='MainController',
  full_name='com.revolutionlandscaping.businessmanager.MainController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_accounts', full_name='com.revolutionlandscaping.businessmanager.MainController.get_accounts', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_accounts', full_name='com.revolutionlandscaping.businessmanager.MainController.save_accounts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delete_accounts', full_name='com.revolutionlandscaping.businessmanager.MainController.delete_accounts', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_employees', full_name='com.revolutionlandscaping.businessmanager.MainController.get_employees', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_employees', full_name='com.revolutionlandscaping.businessmanager.MainController.save_employees', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delete_employees', full_name='com.revolutionlandscaping.businessmanager.MainController.delete_employees', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_jobs', full_name='com.revolutionlandscaping.businessmanager.MainController.get_jobs', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_jobs', full_name='com.revolutionlandscaping.businessmanager.MainController.save_jobs', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delete_jobs', full_name='com.revolutionlandscaping.businessmanager.MainController.delete_jobs', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=1032,
)

_COMMONACTION.fields_by_name['request'].message_type = business__manager__model__pb2._UIBUSINESSMANAGERREQUEST
_COMMONACTION.fields_by_name['response'].message_type = business__manager__model__pb2._UIBUSINESSMANAGERRESPONSE
_MAINCONTROLLER.fields_by_name['get_accounts'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['save_accounts'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['delete_accounts'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['get_employees'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['save_employees'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['delete_employees'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['get_jobs'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['save_jobs'].message_type = _COMMONACTION
_MAINCONTROLLER.fields_by_name['delete_jobs'].message_type = _COMMONACTION
DESCRIPTOR.message_types_by_name['CommonAction'] = _COMMONACTION
DESCRIPTOR.message_types_by_name['MainController'] = _MAINCONTROLLER

CommonAction = _reflection.GeneratedProtocolMessageType('CommonAction', (_message.Message,), dict(
  DESCRIPTOR = _COMMONACTION,
  __module__ = 'business_manager_controller_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.CommonAction)
  ))
_sym_db.RegisterMessage(CommonAction)

MainController = _reflection.GeneratedProtocolMessageType('MainController', (_message.Message,), dict(
  DESCRIPTOR = _MAINCONTROLLER,
  __module__ = 'business_manager_controller_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.MainController)
  ))
_sym_db.RegisterMessage(MainController)


# @@protoc_insertion_point(module_scope)
