# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_manager_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='business_manager_model.proto',
  package='com.revolutionlandscaping.businessmanager',
  syntax='proto3',
  serialized_pb=_b('\n\x1c\x62usiness_manager_model.proto\x12)com.revolutionlandscaping.businessmanager\"\x86\x01\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x0b\n\x03zip\x18\x07 \x01(\t\x12\r\n\x05phone\x18\x08 \x01(\t\"R\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x13\n\x0bhourly_rate\x18\x04 \x01(\x01\"\x81\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0b\x66ixed_price\x18\x05 \x01(\x01\x12\x13\n\x0bhourly_rate\x18\x06 \x01(\x01\x12\r\n\x05hours\x18\x07 \x01(\x01\"\xf5\x01\n\x18UIBusinessManagerRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x44\n\x08\x61\x63\x63ounts\x18\x02 \x03(\x0b\x32\x32.com.revolutionlandscaping.businessmanager.Account\x12\x46\n\temployees\x18\x03 \x03(\x0b\x32\x33.com.revolutionlandscaping.businessmanager.Employee\x12<\n\x04jobs\x18\x04 \x03(\x0b\x32..com.revolutionlandscaping.businessmanager.Job\"\xe7\x01\n\x19UIBusinessManagerResponse\x12\x44\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x32.com.revolutionlandscaping.businessmanager.Account\x12\x46\n\temployees\x18\x02 \x03(\x0b\x32\x33.com.revolutionlandscaping.businessmanager.Employee\x12<\n\x04jobs\x18\x03 \x03(\x0b\x32..com.revolutionlandscaping.businessmanager.Jobb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='com.revolutionlandscaping.businessmanager.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.revolutionlandscaping.businessmanager.Account.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='com.revolutionlandscaping.businessmanager.Account.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='com.revolutionlandscaping.businessmanager.Account.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='com.revolutionlandscaping.businessmanager.Account.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='com.revolutionlandscaping.businessmanager.Account.city', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='com.revolutionlandscaping.businessmanager.Account.state', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zip', full_name='com.revolutionlandscaping.businessmanager.Account.zip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='com.revolutionlandscaping.businessmanager.Account.phone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=210,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='com.revolutionlandscaping.businessmanager.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.revolutionlandscaping.businessmanager.Employee.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='com.revolutionlandscaping.businessmanager.Employee.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='com.revolutionlandscaping.businessmanager.Employee.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hourly_rate', full_name='com.revolutionlandscaping.businessmanager.Employee.hourly_rate', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=294,
)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='com.revolutionlandscaping.businessmanager.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.revolutionlandscaping.businessmanager.Job.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='com.revolutionlandscaping.businessmanager.Job.account_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='com.revolutionlandscaping.businessmanager.Job.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='com.revolutionlandscaping.businessmanager.Job.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixed_price', full_name='com.revolutionlandscaping.businessmanager.Job.fixed_price', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hourly_rate', full_name='com.revolutionlandscaping.businessmanager.Job.hourly_rate', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hours', full_name='com.revolutionlandscaping.businessmanager.Job.hours', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=426,
)


_UIBUSINESSMANAGERREQUEST = _descriptor.Descriptor(
  name='UIBusinessManagerRequest',
  full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accounts', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest.accounts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='employees', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest.employees', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jobs', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest.jobs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=674,
)


_UIBUSINESSMANAGERRESPONSE = _descriptor.Descriptor(
  name='UIBusinessManagerResponse',
  full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accounts', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse.accounts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='employees', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse.employees', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jobs', full_name='com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse.jobs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=908,
)

_UIBUSINESSMANAGERREQUEST.fields_by_name['accounts'].message_type = _ACCOUNT
_UIBUSINESSMANAGERREQUEST.fields_by_name['employees'].message_type = _EMPLOYEE
_UIBUSINESSMANAGERREQUEST.fields_by_name['jobs'].message_type = _JOB
_UIBUSINESSMANAGERRESPONSE.fields_by_name['accounts'].message_type = _ACCOUNT
_UIBUSINESSMANAGERRESPONSE.fields_by_name['employees'].message_type = _EMPLOYEE
_UIBUSINESSMANAGERRESPONSE.fields_by_name['jobs'].message_type = _JOB
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['UIBusinessManagerRequest'] = _UIBUSINESSMANAGERREQUEST
DESCRIPTOR.message_types_by_name['UIBusinessManagerResponse'] = _UIBUSINESSMANAGERRESPONSE

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'business_manager_model_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.Account)
  ))
_sym_db.RegisterMessage(Account)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'business_manager_model_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.Employee)
  ))
_sym_db.RegisterMessage(Employee)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'business_manager_model_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.Job)
  ))
_sym_db.RegisterMessage(Job)

UIBusinessManagerRequest = _reflection.GeneratedProtocolMessageType('UIBusinessManagerRequest', (_message.Message,), dict(
  DESCRIPTOR = _UIBUSINESSMANAGERREQUEST,
  __module__ = 'business_manager_model_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.UIBusinessManagerRequest)
  ))
_sym_db.RegisterMessage(UIBusinessManagerRequest)

UIBusinessManagerResponse = _reflection.GeneratedProtocolMessageType('UIBusinessManagerResponse', (_message.Message,), dict(
  DESCRIPTOR = _UIBUSINESSMANAGERRESPONSE,
  __module__ = 'business_manager_model_pb2'
  # @@protoc_insertion_point(class_scope:com.revolutionlandscaping.businessmanager.UIBusinessManagerResponse)
  ))
_sym_db.RegisterMessage(UIBusinessManagerResponse)


# @@protoc_insertion_point(module_scope)
